### ISSUE TITLE
Problem: Pending txHash can't be found in explorer or getTransaction method

### ISSUE THREAD

**Issue by kuoweilai** [crypto-org-chain/cronos-blockscout#62] opened 2021-11-29 01:45 UTC
I don't know why my issue disappeared, so I posted it again.

The pending txHash I received from websocket subscribtion can't be found in explorer or getTransaction method in web3

**Comment by tomtau** [comment] 2021-12-01 02:11
it seems this is a duplicate of https://github.com/crypto-org-chain/cronos-blockscout/issues/59

**Closed as completed by tomtau** 2021-12-01 02:11 UTC
